import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "../globals.css";
import React from "react";
import {ClerkProvider} from "@clerk/nextjs";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Authication",
    keywords: ["Next.js", "Authentication", "Auth"],
    authors: [{name: "Your Name", url: "https://yourwebsite.com"}],
    creator: "Your Name",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
      <ClerkProvider>

        <html lang="en">
        <body
            className={`${inter.className} bg-dark-1 h-screen flex items-center justify-center`}
        >
        {children}
        </body>
        </html>
      </ClerkProvider>
    );
}
